apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretless
  namespace: cityapp
---
apiVersion: v1
kind: Service
metadata:
  name: secretless
  namespace: cityapp
spec:
  selector:
    app: secretless
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secretless
  namespace: cityapp
spec:
  ingressClassName: nginx
  rules:
  - host: secretless.cityapp.vx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secretless
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretless
  namespace: cityapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretless
  template:
    metadata:
      labels:
        app: secretless
    spec:
      serviceAccountName: secretless
      containers:
      - name: cityapp
        image: docker.io/joetanx/cityapp:php
        imagePullPolicy: IfNotPresent
        env:
        - name: DBADDR
          value: 127.0.0.1
        - name: DBUSER
          value: ''
        - name: DBPASS
          value: ''
      - name: secretless
        image: docker.io/cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        args: ["-f", "/etc/secretless/secretless-cm.yaml"]
        env:
        - name: JWT_TOKEN_PATH
          value: /var/run/secrets/tokens/jwt
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: apps-cm
        volumeMounts:
        - mountPath: /etc/secretless
          name: config
          readOnly: true
        - mountPath: /var/run/secrets/tokens
          name: jwt-token
      volumes:
      - name: jwt-token
        projected:
          sources:
          - serviceAccountToken:
              path: jwt
              expirationSeconds: 6000
              audience: vxlab
      - name: config
        configMap:
          name: secretless-cm
