---
apiVersion: v1
kind: Service
metadata:
  name: follower
  labels:
    app: follower
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: follower
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follower
  template:
    metadata:
      labels:
        app: follower
        name: follower
        role: follower
    spec:
      serviceAccountName: authn-k8s-sa
      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory
      initContainers:
      - name: authenticator
        image: cyberark/dap-seedfetcher
        imagePullPolicy: IfNotPresent
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FOLLOWER_HOSTNAME
            value: follower
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: CONJUR_AUTHN_LOGIN
            value: host/conjur/followers/k8s-follower
        envFrom:
          - configMapRef:
              name: conjur-connect-followers
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur
      containers:
      - name: conjur-appliance
        image: registry.tld/conjur-appliance:12.4.1
        command: ["/tmp/seedfile/start-follower.sh"]
        imagePullPolicy: IfNotPresent
        env:
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/demo
        ports:
        - containerPort: 443
          name: https
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true