---
apiVersion: v1
kind: Namespace
metadata:
  name: conjur
---
apiVersion: v1
kind: Namespace
metadata:
  name: cityapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authn-k8s-sa
  namespace: conjur
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-authenticator
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "serviceaccounts"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conjur-authenticator-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: authn-k8s-sa
  namespace: conjur
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator